language: php
php:
  - 7.2
  - 7.3
  - nightly
  
dist: trusty

# upgrade to container-based travis
sudo: false

matrix:
  fast_finish: true
  
before_script:
  - composer self-update
  - composer install --dev

script: 
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - travis@b-zik.de
